// Code generated by protoc-gen-go. DO NOT EDIT.
// source: registry.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ActionType int32

const (
	ActionType_None        ActionType = 0
	ActionType_Normal      ActionType = 1
	ActionType_Replication ActionType = 2
)

var ActionType_name = map[int32]string{
	0: "None",
	1: "Normal",
	2: "Replication",
}

var ActionType_value = map[string]int32{
	"None":        0,
	"Normal":      1,
	"Replication": 2,
}

func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}

func (ActionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

type RegisterRequest struct {
	Action               ActionType       `protobuf:"varint,1,opt,name=action,proto3,enum=com.busgo.registry.proto.ActionType" json:"action,omitempty"`
	Instance             *ServiceInstance `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegisterRequest) Reset()         { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()    {}
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{0}
}

func (m *RegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRequest.Unmarshal(m, b)
}
func (m *RegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRequest.Marshal(b, m, deterministic)
}
func (m *RegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRequest.Merge(m, src)
}
func (m *RegisterRequest) XXX_Size() int {
	return xxx_messageInfo_RegisterRequest.Size(m)
}
func (m *RegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRequest proto.InternalMessageInfo

func (m *RegisterRequest) GetAction() ActionType {
	if m != nil {
		return m.Action
	}
	return ActionType_None
}

func (m *RegisterRequest) GetInstance() *ServiceInstance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type RegisterResponse struct {
	Code                 int32            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string           `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Instance             *ServiceInstance `protobuf:"bytes,3,opt,name=instance,proto3" json:"instance,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *RegisterResponse) Reset()         { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()    {}
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{1}
}

func (m *RegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterResponse.Unmarshal(m, b)
}
func (m *RegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterResponse.Marshal(b, m, deterministic)
}
func (m *RegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterResponse.Merge(m, src)
}
func (m *RegisterResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterResponse.Size(m)
}
func (m *RegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterResponse proto.InternalMessageInfo

func (m *RegisterResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *RegisterResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RegisterResponse) GetInstance() *ServiceInstance {
	if m != nil {
		return m.Instance
	}
	return nil
}

type ServiceInstance struct {
	Segment              string            `protobuf:"bytes,1,opt,name=segment,proto3" json:"segment,omitempty"`
	ServiceName          string            `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	Ip                   string            `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32             `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Metadata             map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RegTimestamp         int64             `protobuf:"varint,6,opt,name=regTimestamp,proto3" json:"regTimestamp,omitempty"`
	UpTimestamp          int64             `protobuf:"varint,7,opt,name=upTimestamp,proto3" json:"upTimestamp,omitempty"`
	RenewTimestamp       int64             `protobuf:"varint,8,opt,name=renewTimestamp,proto3" json:"renewTimestamp,omitempty"`
	DirtyTimestamp       int64             `protobuf:"varint,9,opt,name=dirtyTimestamp,proto3" json:"dirtyTimestamp,omitempty"`
	LatestTimestamp      int64             `protobuf:"varint,10,opt,name=latestTimestamp,proto3" json:"latestTimestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ServiceInstance) Reset()         { *m = ServiceInstance{} }
func (m *ServiceInstance) String() string { return proto.CompactTextString(m) }
func (*ServiceInstance) ProtoMessage()    {}
func (*ServiceInstance) Descriptor() ([]byte, []int) {
	return fileDescriptor_41af05d40a615591, []int{2}
}

func (m *ServiceInstance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInstance.Unmarshal(m, b)
}
func (m *ServiceInstance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInstance.Marshal(b, m, deterministic)
}
func (m *ServiceInstance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInstance.Merge(m, src)
}
func (m *ServiceInstance) XXX_Size() int {
	return xxx_messageInfo_ServiceInstance.Size(m)
}
func (m *ServiceInstance) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInstance.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInstance proto.InternalMessageInfo

func (m *ServiceInstance) GetSegment() string {
	if m != nil {
		return m.Segment
	}
	return ""
}

func (m *ServiceInstance) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceInstance) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ServiceInstance) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *ServiceInstance) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ServiceInstance) GetRegTimestamp() int64 {
	if m != nil {
		return m.RegTimestamp
	}
	return 0
}

func (m *ServiceInstance) GetUpTimestamp() int64 {
	if m != nil {
		return m.UpTimestamp
	}
	return 0
}

func (m *ServiceInstance) GetRenewTimestamp() int64 {
	if m != nil {
		return m.RenewTimestamp
	}
	return 0
}

func (m *ServiceInstance) GetDirtyTimestamp() int64 {
	if m != nil {
		return m.DirtyTimestamp
	}
	return 0
}

func (m *ServiceInstance) GetLatestTimestamp() int64 {
	if m != nil {
		return m.LatestTimestamp
	}
	return 0
}

func init() {
	proto.RegisterEnum("com.busgo.registry.proto.ActionType", ActionType_name, ActionType_value)
	proto.RegisterType((*RegisterRequest)(nil), "com.busgo.registry.proto.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "com.busgo.registry.proto.RegisterResponse")
	proto.RegisterType((*ServiceInstance)(nil), "com.busgo.registry.proto.ServiceInstance")
	proto.RegisterMapType((map[string]string)(nil), "com.busgo.registry.proto.ServiceInstance.MetadataEntry")
}

func init() { proto.RegisterFile("registry.proto", fileDescriptor_41af05d40a615591) }

var fileDescriptor_41af05d40a615591 = []byte{
	// 443 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xc1, 0x8e, 0xd3, 0x30,
	0x10, 0x86, 0x49, 0xd2, 0x76, 0xd3, 0x29, 0xb4, 0xd1, 0x88, 0x43, 0xb4, 0xa7, 0xa8, 0x42, 0x28,
	0xec, 0x21, 0x87, 0xee, 0x01, 0x04, 0x5c, 0x40, 0xda, 0x03, 0x07, 0x7a, 0xf0, 0xee, 0x89, 0x9b,
	0x9b, 0x8e, 0x22, 0x8b, 0x26, 0x36, 0xb6, 0xbb, 0x28, 0x4f, 0xc0, 0x1b, 0xf0, 0x42, 0xbc, 0x18,
	0x8a, 0x93, 0x6c, 0x36, 0x95, 0x16, 0x55, 0xdc, 0xec, 0x7f, 0xbe, 0x3f, 0xfe, 0xc7, 0x19, 0xc3,
	0x52, 0x53, 0x21, 0x8c, 0xd5, 0x75, 0xa6, 0xb4, 0xb4, 0x12, 0xe3, 0x5c, 0x96, 0xd9, 0xee, 0x68,
	0x0a, 0x99, 0x8d, 0x2b, 0xeb, 0xdf, 0x1e, 0xac, 0x98, 0x93, 0x48, 0x33, 0xfa, 0x71, 0x24, 0x63,
	0xf1, 0x23, 0xcc, 0x78, 0x6e, 0x85, 0xac, 0x62, 0x2f, 0xf1, 0xd2, 0xe5, 0xe6, 0x55, 0xf6, 0x94,
	0x3d, 0xfb, 0xe4, 0xb8, 0xbb, 0x5a, 0x11, 0xeb, 0x3c, 0x78, 0x03, 0xa1, 0xa8, 0x8c, 0xe5, 0x55,
	0x4e, 0xb1, 0x9f, 0x78, 0xe9, 0x62, 0xf3, 0xe6, 0x69, 0xff, 0x2d, 0xe9, 0x7b, 0x91, 0xd3, 0x97,
	0xce, 0xc0, 0x1e, 0xac, 0xeb, 0x5f, 0x1e, 0x44, 0x43, 0x30, 0xa3, 0x64, 0x65, 0x08, 0x11, 0x26,
	0xb9, 0xdc, 0x93, 0xcb, 0x35, 0x65, 0x6e, 0x8d, 0x31, 0x5c, 0x94, 0x64, 0x0c, 0x2f, 0xda, 0xe3,
	0xe6, 0xac, 0xdf, 0x8e, 0x92, 0x04, 0xff, 0x9f, 0xe4, 0x4f, 0x00, 0xab, 0x93, 0x6a, 0x73, 0xa8,
	0xa1, 0xa2, 0xa4, 0xca, 0xba, 0x2c, 0x73, 0xd6, 0x6f, 0x31, 0x81, 0x85, 0x69, 0xe1, 0x2d, 0x2f,
	0xfb, 0x48, 0x8f, 0x25, 0x5c, 0x82, 0x2f, 0x94, 0x0b, 0x34, 0x67, 0xbe, 0x50, 0x4d, 0x53, 0x4a,
	0x6a, 0x1b, 0x4f, 0xda, 0xa6, 0x9a, 0x35, 0xde, 0x42, 0x58, 0x92, 0xe5, 0x7b, 0x6e, 0x79, 0x3c,
	0x4d, 0x82, 0x74, 0xb1, 0x79, 0x7b, 0x76, 0xf4, 0xec, 0x6b, 0xe7, 0xbc, 0xa9, 0xac, 0xae, 0xd9,
	0xc3, 0x87, 0x70, 0x0d, 0xcf, 0x35, 0x15, 0x77, 0xa2, 0x24, 0x63, 0x79, 0xa9, 0xe2, 0x59, 0xe2,
	0xa5, 0x01, 0x1b, 0x69, 0x4d, 0xfc, 0xa3, 0x1a, 0x90, 0x0b, 0x87, 0x3c, 0x96, 0xf0, 0x75, 0x33,
	0x5d, 0x15, 0xfd, 0x1c, 0xa0, 0xd0, 0x41, 0x27, 0x6a, 0xc3, 0xed, 0x85, 0xb6, 0xf5, 0xc0, 0xcd,
	0x5b, 0x6e, 0xac, 0x62, 0x0a, 0xab, 0x03, 0xb7, 0x64, 0xec, 0x00, 0x82, 0x03, 0x4f, 0xe5, 0xcb,
	0x0f, 0xf0, 0x62, 0xd4, 0x1a, 0x46, 0x10, 0x7c, 0xa7, 0xba, 0xfb, 0x03, 0xcd, 0x12, 0x5f, 0xc2,
	0xf4, 0x9e, 0x1f, 0x8e, 0xfd, 0xbd, 0xb7, 0x9b, 0xf7, 0xfe, 0x3b, 0xef, 0xea, 0x1a, 0x60, 0x18,
	0x56, 0x0c, 0x61, 0xb2, 0x95, 0x15, 0x45, 0xcf, 0x10, 0x60, 0xb6, 0x95, 0xba, 0xe4, 0x87, 0xc8,
	0xc3, 0x15, 0x2c, 0x18, 0xa9, 0x83, 0xc8, 0x79, 0x03, 0x46, 0xfe, 0xc6, 0xf6, 0x8f, 0x43, 0xd7,
	0xdd, 0x25, 0x23, 0x87, 0x50, 0x77, 0x63, 0x89, 0xff, 0x18, 0xa7, 0x93, 0x37, 0x75, 0x79, 0x75,
	0x0e, 0xda, 0x4e, 0xf9, 0xe7, 0xc9, 0x37, 0x5f, 0xed, 0x76, 0x33, 0x57, 0xbd, 0xfe, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x8f, 0xca, 0x29, 0x95, 0xcc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RegistryServiceClient is the client API for RegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistryServiceClient interface {
	// register a service instance
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
}

type registryServiceClient struct {
	cc *grpc.ClientConn
}

func NewRegistryServiceClient(cc *grpc.ClientConn) RegistryServiceClient {
	return &registryServiceClient{cc}
}

func (c *registryServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, "/com.busgo.registry.proto.RegistryService/register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistryServiceServer is the server API for RegistryService service.
type RegistryServiceServer interface {
	// register a service instance
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
}

// UnimplementedRegistryServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRegistryServiceServer struct {
}

func (*UnimplementedRegistryServiceServer) Register(ctx context.Context, req *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}

func RegisterRegistryServiceServer(s *grpc.Server, srv RegistryServiceServer) {
	s.RegisterService(&_RegistryService_serviceDesc, srv)
}

func _RegistryService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistryServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.busgo.registry.proto.RegistryService/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistryServiceServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.busgo.registry.proto.RegistryService",
	HandlerType: (*RegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "register",
			Handler:    _RegistryService_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "registry.proto",
}
